### ISSUE TITLE
Trouble merging with hocr-pdf

### ISSUE THREAD

**Issue by drewreece** [tmbdev/hocr-tools#106]
I'm having issues merging hocr & jpeg files into a searchable PDF. I generated the hocr with ocropy, hopefully that is correct. I used the run-test as an example workflow. Neither the run-test output or my source will generate a working PDF.

I attempt to merge with hocr-pdf . > test.pdf but only get an image in the PDF. Preview & the PDF.js tool in Firefox have no searchable content. Are there better tools to see what is happening? 

I am using hocr-tools 1.1.1 & Python 2.7.12 on OS X 10.9.5. 
I also tried hocr-tools on a debian system & got the same result.

Are there any sample files to try merging to see if it can work? 

My test directory looks like…
ls temp-output
  temp.hocr
  temp.jpg
  test.pdf

Here is a zip of that directory incase testing helps.
https://www.dropbox.com/s/j6lpx2kgfao6143/temp-output.zip

**Comment by zuphilip** [comment]
Indeed, the hocr-pdf is currently only working when there are `ocrx_word` present in the hocr file, such as it is the case for the output of tesseract, but not the output of ocropy. I tried a simple fix in https://github.com/tmbdev/hocr-tools/pull/107 which should in these cases switch to `ocr_line` instead. Any testing or reviewing of this PR is appreciated.

**Comment by drewreece** [comment]
Fixed by #107

Excellent, thanks all.
