### ISSUE TITLE
Requiring authentication for accessing the rest api

### ISSUE THREAD

**Issue by Rob1080** [tmbdev/hocr-tools#109]
Hi,

I may be missing something obvious, but how do we "lock down" access to the rest api?
Thanks
Rob

**Comment by zuphilip** [comment]
The `hocr-tools` are a bunch of Python scripts and there is no REST API. What do you mean exactly?

**Comment by Rob1080** [comment]
Ah, I somehow commented on the wrong repo. Sorry to waste your time.
