### ISSUE TITLE
hocr-pdf: issue with search and copy/paste in macOS Preview.app

### ISSUE THREAD

**Issue by joao** [tmbdev/hocr-tools#111]
The Preview.app is the default PDF reader for macOS.
When using hocr-pdf to generate a PDF file, from an image + hocr file, the generated PDF works well for search, and copy/paste in Acrobat, PDF.js and others, but not Preview. You can't search in Preview, though you can select text and copy/paste to another document, but are just blank characters.

Anyone knows of a specific reason for this to happen?

**Comment by amitdo** [comment]
This comment from Tesseract might be related:
https://github.com/tesseract-ocr/tesseract/blob/9038faf4365a/api/pdfrenderer.cpp#L293

**Comment by joao** [comment]
They would be related to highlighting and selection, but search actually doesn't work. And in my tests I even put a baseline of 0, or none at all.
Search should work independently, even if the highlight/selection would not work that well.

Seems it simply doesn't extract and recognise text content.

**Comment by amitdo** [comment]
I believe that broken highlighting will also mean broken search and a fix for one of them will also fix the other one.

**Comment by amitdo** [comment]
>in my tests I even put a baseline of 0, or none at all.

Please explain how you did this test.

**Comment by joao** [comment]
An extract from an hOCR file:


    <div class="ocr_page" id="page_1" title='bbox 0 0 2481 3510'>
      
      <div class='ocr_carea' id='block_1' title="bbox 172 217 1164 1051">
        
        <p class='ocr_par' id='par_1' title="bbox 172 217 1164 1051">
          
          <span class="ocr_line" id="line_1" title="bbox 183 217 1095 329; baseline 0 0">


With or without a flat baseline, the generated PDF works perfectly on Acrobat and PDF.js, but not on Preview — this using the hocr-pdf utility. One is able to select the text in Preview, but not search or copy/paste returns blank.

This is if I understood correctly the Tesseract link you gave, which indicated that Preview preferred flat baselines.

**Comment by zuphilip** [comment]
I am sorry, but I don't have a mac for testing and I am really unsure what the problem could be. We use here an (doubly) invisible font to make the text layer in the PDF. I don't know whether some PDF reader don't like that.

@joao I will close this issue now, but feel free reopen if the problem persists and you think there is something we can help you with.
