### ISSUE TITLE
Error while using hocr-pdf file

### ISSUE THREAD

**Issue by shekarnode** [tmbdev/hocr-tools#121]
While using the below command i m getting error related to character 
help out please

```
hocr-pdf . > out.pdf
Traceback (most recent call last):
  File "C:\Python36\Scripts\hocr-pdf.py", line 143, in <module>
    export_pdf(args.imgdir, 300)
  File "C:\Python36\Scripts\hocr-pdf.py", line 70, in export_pdf
    pdf.save()
  File "c:\python36\lib\site-packages\reportlab\pdfgen\canvas.py", line 1237, in save
    self._doc.SaveToFile(self._filename, self)
  File "c:\python36\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 224, in SaveToFile
    f.write(data)
  File "C:\Python36\Scripts\hocr-pdf.py", line 47, in write
    sys.stdout.write(data)
  File "c:\python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 11-14: character maps to <undefined>
```

**Comment by stweil** [comment]
Can you provide a hOCR file which causes this error? How did you create it?

**Comment by shekarnode** [comment]
I used Tesseract 4.0.0 to generate hocr
[https://ufile.io/jbtm9](Hocr file)

This is the image for above generate Hocr
![e3_out](https://user-images.githubusercontent.com/3267543/39908554-39e7c794-550c-11e8-9ded-251744d0c1a3.png)

**Comment by shekarnode** [comment]
@zuphilip 
1. i  was using png image for conversion , now i replaced it with jpg.
2. Environment - Windows
3. Python 3.6.4
4.well i was using cmd to get output , tried with git bash , i got pdf as output but it was just a normal pdf i.e. not in searchable format.

**Comment by amitdo** [comment]
Tesseract has an option to output to pdf. Did you tried it?

**Comment by zuphilip** [comment]
> are you able to generate searchable pdf ?

Yes, I see a searchable PDF, but I am working on Linux.

For windows terminal the encoding can be a problem. You can check the encoding for python in windows terminal by starting `python` and then type
```sh
>>> import sys
>>> sys.stdout.encoding
```

If that is now UTF-8 then you can try to run the command with `PYTHONIOENCODING=UTF-8 ` in front, i.e.
```
PYTHONIOENCODING=UTF-8 hocr-pdf . > out.pdf
```

> i got pdf as output but it was just a normal pdf i.e. not in searchable format.

This is with the git bash on windows, right? Can you upload your result here?

**Comment by shekarnode** [comment]
@zuphilip 
[out.pdf](https://github.com/tmbdev/hocr-tools/files/2007985/out.pdf)
this the pdf file being generated 

@amitdo 
i have tried generating searchable pdf from tesseract also:
the commands are provided over [here](https://github.com/tesseract-ocr/tesseract/wiki/Command-Line-Usage) were used .
still the output is not searchable fromat its just simple pdf with image.

**Comment by zuphilip** [comment]
@shekarnode There is text in your generated PDF and I can search for text as well.

**Comment by amitdo** [comment]
The pdf produced by Tesseract is also searchable.
