### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' (negative bbox attr)

### ISSUE THREAD

**Issue by skylord123** [tmbdev/hocr-tools#127]
```
	Message: Error from hocr-pdf.exe: [10920] Failed to execute script hocr-pdf
	Traceback (most recent call last):
	  File "hocr-pdf", line 163, in 
	  File "hocr-pdf", line 69, in export_pdf
	  File "hocr-pdf", line 81, in add_text_layer
	AttributeError: 'NoneType' object has no attribute 'group'
	StackTrace: coldfusion.runtime.CustomException: Error from hocr-pdf.exe: [10920] Failed to execute script hocr-pdf
	Traceback (most recent call last):
	  File "hocr-pdf", line 163, in 
	  File "hocr-pdf", line 69, in export_pdf
	  File "hocr-pdf", line 81, in add_text_layer
```

Looks to have to do with this line not matching negative bounding boxes:
https://github.com/tmbdev/hocr-tools/blob/master/hocr-pdf#L76

I hit this issue on a 60 page PDF around page 14 or so. I don't know why I got negative bounding boxes but It's a thing and caused my code to fail because of it. Updating the above mentioned line to match negative numbers fixes this issue and allows my PDF to be created correctly.

**Comment by stweil** [comment]
It would be good to have an example for negative bounding boxes. Is it possible to extract the PDF page which causes that and provide it here? Or has someone else an example?

**Comment by kba** [comment]
How was the input document created? All values of an hocr `bbox` [must be unsigned integers](http://kba.cloud/hocr-spec/1.2/#bbox), absolute coordinates on the page. It doesn't make sense to have a bounding box extend beyond the page. Are you creating bounding boxes across double pages?

It is more sensible to fix this upstream in whatever tool created the hocr, e.g. by clipping values to zero.

**Comment by skylord123** [comment]
I didn't know that about the hocr bbox. I believe the issue may reside in gcv2hocr tool I use to convert google vision responses to hocr. I'm going to do some further testing and report back with my findings. I cannot share the PDF file I am using because it is confidential.

I found another PDF that has 50 pages that is having a similar issue. It is a 50-page scanned document and the issue occurs a couple pages in. The weird thing is the page that has the issue doesn't have any text near the edge of the page. I wonder how I am getting negative values..

I will report back after further tesitng.

**Comment by skylord123** [comment]
I've opened a PR at gcv2hocr project. This fixes the error by generating HOCR that is in compliance with the spec (forcing bbox to use unsigned integers or default to 0).

Closing this issue as my problem is resolved. I hope this helps others that run into the same issue.

**Comment by stweil** [comment]
Thank you for clarifying this issue.
