### ISSUE TITLE
All tools should have a -h/--help option

### ISSUE THREAD

**Issue by kba** [tmbdev/hocr-tools#13]
Not all the tools support a help flag. We should add this as a baseline so users can get at least minimal usage info on the command line.

Tools without -h/--help (c.f. [smoke.tsht](../test/smoke.tsht)):
- [x] hocr-check
- [x] hocr-combine
- [x] hocr-extract-images
- [x] hocr-lines
- [x] hocr-merge-dc

Plus possibly those that do not run at the moment because of PyXML/lxml #9

**Comment by zuphilip** [comment]
Moreover, we can check that the help will be shown, if a command is called without any argument. I am not sure how consistently this is already the case at the moment.

**Comment by kba** [comment]
Some commands expect to read from `STDIN` and will just wait for input if no argument is given.
