### ISSUE TITLE
Possible to add HOCR to existing PDF?

### ISSUE THREAD

**Issue by SakeviYokoyama** [tmbdev/hocr-tools#130]
Given an existing PDF and an HOCR file, is there an option to take that HOCR file and merge it into the existing PDF? Unless I overlooked something, The only option I could find was to create a PDF from images/HOCR files. If not, maybe this is a useful feature to add?

**Comment by jsbien** [comment]
Convert PDF to DjVu, convert hOCR to djvused, apply djvused to DjVu, export DjVu as PDF - it should work, but I'm not sure the quality of PDF will be preserved.

**Comment by zuphilip** [comment]
I am not familiar with any DjVu workflow, but I would rather have thought something like:
1. Convert PDF to JPEG
2. Take these JPEG images together with the hOCR files as input of `hocr-pdf` script
3. The output is already a PDF with a text overlay
