### ISSUE TITLE
DeprecationWarning about decodestring

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/hocr-tools#145]
With Python 3 I see now for hocr-pdf the following warning:
```
hocr-pdf:145: DeprecationWarning: decodestring() is a deprecated alias since
Python 3.1, use decodebytes()
  uncompressed = bytearray(zlib.decompress(base64.decodestring(font)))
```

Can we fix that easily such that also Python 2 is still supported?

**Comment by stweil** [comment]
@zuphilip, is support for Python 2 still needed? Or can we drop it in the near future?

**Comment by zuphilip** [comment]
Ocropus itself is currently Python 2 only. There is a PR to make it Python 2+3 compatible, but that still needs some time to test and review. I am skeptical that we should switch to Python 3 only.

**Comment by stweil** [comment]
OCR-D requires Python 3 for its Python scripts.

**Comment by zuphilip** [comment]
I know.

But there were already quite some discussion about that in the ocropus repository, and supporting Python 2 seems still important in these contexts.
