### ISSUE TITLE
Clean up coding style

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/hocr-tools#15]
See https://github.com/tmbdev/hocr-tools/pull/14#discussion_r63843228 and https://travis-ci.org/UB-Mannheim/hocr-tools/builds/131389791 .

**Comment by stweil** [comment]
See also [PEP-8](https://www.python.org/dev/peps/pep-0008/), the _Style Guide for Python Code_.

**Comment by stweil** [comment]
PR #141 fixed the last style issues and enabled PEP8 style checking in Travis CI.
