### ISSUE TITLE
alto input?

### ISSUE THREAD

**Issue by jtlz2** [tmbdev/hocr-tools#155]
I am trying to use your excellent tools to compare alto files from ABBYY and tesseract, but I haven't found a reliable way to convert the alto into hocr in order to do so.

Do you have any plans to support alto input?

I have tried to get [ocr-fileformat](https://github.com/UB-Mannheim/ocr-fileformat) to do the conversion - so far in vain.

Thanks for all help

**Comment by zuphilip** [comment]
The hocr-tools are tools for working with hocr files. A transformation from ALTO to hocr is out-of-scope here, but the main purpose of ocr-fileformat. This transformation should already been supported by ocr-fileformat. Let us know there, if you have any problems with that.

**Comment by jtlz2** [comment]
Huge thanks and sorry to pollute - see https://github.com/UB-Mannheim/ocr-fileformat/issues/89 where I have described the problem at hand.
