### ISSUE TITLE
Switch from PyXML to BeautifulSoup

### ISSUE THREAD

**Issue by danvk** [tmbdev/hocr-tools#2]
PyXML hasn't been updated in [10+ years][1]. Would you consider moving these tools over to something like [BeautifulSoup][soup] which is on PyPI and easier to install?

Here's what `hocr-lines` looks like using BeautifulSoup:

```python
#!/usr/bin/env python

import re
import sys
from bs4 import BeautifulSoup

if len(sys.argv)>1:
    stream = open(sys.argv[1])
else:
    stream = sys.stdin

soup = BeautifulSoup(stream)
for line in soup.select('.ocr_line'):
    print re.sub(r'\s+', ' ', line.text)
```

[1]: http://sourceforge.net/projects/pyxml/files/pyxml/
[soup]: http://www.crummy.com/software/BeautifulSoup/

**Comment by zuphilip** [comment]
In our fork I moved to `lxml` (at the moment just for one file), see https://github.com/UB-Mannheim/hocr-tools/commit/dc04f47c5fd0c8ae56c5329c0810c35ac6429b8c . No installation was needed at all (at least on my system).

@tmbdev Let me know if that is interesting for you. I could also prepare a PR. Or what are your plans for this repo overall?

**Comment by zuphilip** [comment]
The latest PR https://github.com/tmbdev/hocr-tools/pull/6 changed to `lxml` for most of the scripts.
