### ISSUE TITLE
Switch to argparse module

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/hocr-tools#20]
In Python 2.7 and later there is a module [`argparse`](https://docs.python.org/3.5/library/argparse.html) that helps with arguments parsing for command line tools. This module is also used in `ocropus` and it looks better structured than the current situation we have.

See also http://www.cyberciti.biz/faq/python-command-line-arguments-argv-example/

**Comment by zuphilip** [comment]
(BTW: Some of the logic at the moment for parsing arguments seems to be incorrect, e.g. https://github.com/tmbdev/hocr-tools/pull/41#discussion-diff-77005028 )

**Comment by stweil** [comment]
See PR #82.
