### ISSUE TITLE
Convert Google Cloud Vision OCR output to hocr.

### ISSUE THREAD

**Issue by dinosauria123** [tmbdev/hocr-tools#26]
I have a question.

I try to use Google Cloud Vision API to OCR.

https://cloud.google.com/vision/

The output of the OCR results including the position of the texts.

I want to convert Google OCR output to hocr format, do you have any ideas ?

**Comment by zuphilip** [comment]
Do you have an example of the output of the Google Cloud Vision API? I just tried the online interface but the results only contains the words each with a bounding polygon, which is not so much to start with...

**Comment by stweil** [comment]
The output is JSON and should contain polygon boxes both for regions with text and for the single words (see https://cloud.google.com/vision/reference/rest/v1/images/annotate), so a conversion to hOCR seems to be possible although much interesting information is missing.

The API supports suggesting languages (https://cloud.google.com/translate/v2/translate-reference#supported_languages), but I did not find support for old German (Fraktur). A short test with old text did not recognize much words.

**Comment by dinosauria123** [comment]
Thank you for the comments.

I tried OCR via Google Vision API, the result is the same from online interface.
I referred this web page.
http://blog.aimanbaharum.com/2016/04/21/ocr-with-google-cloud-vision-api/

Comparing Tesseract hocr output, many info lack from Google Vision API result,
but it seems to contain polygon boxes both for regions with text and for the single words.

I think I need generate the class ocr_page, ocr_carea, ocr_par, and ocr_line from Google Cloud Vision result, thats enough ?

![test](https://cloud.githubusercontent.com/assets/3067670/17273777/75003470-56fc-11e6-9866-1c6cda779d33.jpg)
[test.jpg.json.txt](https://github.com/tmbdev/hocr-tools/files/392160/test.jpg.json.txt)
[out.hocr.txt](https://github.com/tmbdev/hocr-tools/files/392161/out.hocr.txt)

  <div class='ocr_page' id='page_1' title='image "test.jpg"; bbox 0 0 826 1169; ppageno 0'>
   <div class='ocr_carea' id='block_1_1' title="bbox 81 103 738 193">
    <p class='ocr_par' dir='ltr' id='par_1_1' title="bbox 81 103 738 193">
     <span class='ocr_line' id='line_1_1' title="bbox 81 103 738 193; baseline 0.002 -21; x_size 89; x_descenders 20; x_ascenders 21"><span class='ocrx_word' id='word_1_1' title='bbox 81 103 253 173; x_wconf 85' lang='eng' dir='ltr'>This</span>

**Comment by zuphilip** [comment]
Two larger differences are:
 1. There is no information about text lines, i.e. which words are on the same text line
 2. There are no rectangular boxes (`bbox`) but polygon (`poly`) for bounding the text

This means that you cannot come up with this information in a simple transformation of file formats. In general the [hocr format](https://github.com/kba/hocr-spec/blob/master/hocr-spec.md) is quite flexible, i.e. you might just output what is there, and it may still be valid. But the tools based on hocr are expecting normally `ocr_line` and also `bbox`.

**Comment by stweil** [comment]
[UB-Mannheim/ocr-fileformat](https://github.com/UB-Mannheim/ocr-fileformat) might be a better place for a converter from the Google Cloud Vision JSON format to hOCR.

**Comment by dinosauria123** [comment]
Thank you for your kindly helps.

I want to make a searchable pdf from Google Cloud Vision OCR, the exact position / layout of the text is not so important.

I have to learn hocr format, thank you for the information.

I will post this subject to UB-Mannheim/ocr-fileformat. Thank you again for the information.

**Comment by zuphilip** [comment]
Yeah, the `hocr-pdf` is expecting `ocr_line` see https://github.com/tmbdev/hocr-tools/blob/master/hocr-pdf#L65-L66 and `bbox` arguments see https://github.com/tmbdev/hocr-tools/blob/master/hocr-pdf#L59 . I don't think it will do anything without these information.

**Comment by dinosauria123** [comment]
I made gcv2hocr at github.
https://github.com/dinosauria123/gcv2hocr

gcv2hocr converts from Google Cloud Vision OCR output to hocr to make a searchable pdf.
The code is far from complete, but it seems to work my sample file.

Thank you for valuable conversations !

**Comment by stweil** [comment]
This issue is continued on [UB-Mannheim/ocr-fileformat](https://github.com/UB-Mannheim/ocr-fileformat), so I close it here.
