### ISSUE TITLE
UnboundLocalError: local variable 'rawtext' referenced before assignment

### ISSUE THREAD

**Issue by jronallo** [tmbdev/hocr-tools#30]
With some hocr files created by tesseract I get the following error when using hocr-pdf. Here's an example hocr file that causes this error: 
https://drive.google.com/file/d/0ByUq6R632zOwU2ZrOTVMT0ZtdG8/view?usp=sharing

```
raceback (most recent call last):
  File "/usr/bin/hocr-pdf", line 5, in <module>
    pkg_resources.run_script('hocr-tools==0.1', 'hocr-pdf')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1462, in run_script
    exec_(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 41, in exec_
    exec("""exec code in globs, locs""")
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/hocr_tools-0.1-py2.7.egg/EGG-INFO/scripts/hocr-pdf", line 137, in <module>
    
  File "/usr/lib/python2.7/site-packages/hocr_tools-0.1-py2.7.egg/EGG-INFO/scripts/hocr-pdf", line 53, in export_pdf
    
  File "/usr/lib/python2.7/site-packages/hocr_tools-0.1-py2.7.egg/EGG-INFO/scripts/hocr-pdf", line 86, in add_text_layer
    
UnboundLocalError: local variable 'rawtext' referenced before assignment
```

If rawtext is set to an empty string at some point before line 86, then the script completes creating a searchable PDF--yes, a rather poorly OCR'd one, but a PDF nevertheless.

**Comment by stweil** [comment]
Could you please add the image file (/tmp/technician-v9n22-1929-03-09_000420160806-17014-u49zax.jpg), too? I cannot reproduce your test case without it, as I simply get an empty PDF file and no error message. Nevertheless the code is clearly buggy because `rawtext` does not always get a value.

**Comment by jronallo** [comment]
You can get the the image here: https://iiif.lib.ncsu.edu/iiif/technician-v9n22-1929-03-09_0004/full/full/0/default.jpg

**Comment by zuphilip** [comment]
Thank you for the error report and the files. I will look into this now. Can you provide your versions of the python packages you are working with, i.e.
```
python --version
pip freeze
```
:question:

**Comment by zuphilip** [comment]
Okay, I can reproduce the error now.

There is a possible case that `rawtext` is not defined and before [line 86](https://github.com/tmbdev/hocr-tools/blob/master/hocr-pdf#L86) and thereby producing the error (independent of the Python version).

**Comment by stweil** [comment]
PR #33 was pulled now, so the reported bug is fixed.
I noticed that the generated PDF does not support searching when I view it in Firefox for Linux. Firefox for Windows shows a few text parts (visible when all text is selected). Is this a general problem with the PDF files generated by hocr-pdf? Then we should add a new issue for that.

**Comment by zuphilip** [comment]
I can search in the text of the generated PDF under Windows without any problem. If you encounter any other problems then feel free to open a new issue.
