### ISSUE TITLE
Coordinates in bbox must be from top to bottom

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/hocr-tools#32]
From the [hocr specs](https://github.com/kba/hocr-spec/blob/master/hocr-spec.md#5-typesetting-related-elements):
> the bounding box of the page; for pages, the top left corner must be at (0,0), so a typical page bounding box will look like bbox 0 0 2300 3200

**Comment by stweil** [comment]
Which bbox ish wrong?

**Comment by zuphilip** [comment]
You are right. I reported the error upstream in the ocropy repo: https://github.com/tmbdev/ocropy/issues/107
