### ISSUE TITLE
Make hocr-tools fit for Python 3

### ISSUE THREAD

**Issue by kba** [tmbdev/hocr-tools#37]
We should consider making the tools ready for Python 3. Not so much because 2.7 is going away soon (it will be officially developed until 2020)  but because all the problems 2to3 reports are easily fixable, e.g. throwing strings is bad practice in all versions.

The changes to the standard libaries (e.g. `cStringIO` is now `io.StringIO`) make it tedious to use the same code for both versions (and it's generally not recommended). Instead, I propose that we fix the code problems 2to3 reports and ensure (by testing in CI) that the code can be automatically ported to Python 3 and run the tests. At some point in the future, we can then just run 2to3 for good.

**Comment by kba** [comment]
Was mostly implemented by #46, only step left is converting print statements.

**Comment by amitdo** [comment]
>The changes to the standard libaries ... make it tedious **to use the same code for both versions (and it's generally not recommended).** Instead, I propose that we fix the code problems 2to3 reports and ensure (by testing in CI) that the code can be automatically ported to Python 3 and run the tests. At some point in the future, we can then just run 2to3 for good.

 @kba, @zuphilip, FYI
Actually, the recommended way is to use one shared codebase. This is reflected in the official docs: https://docs.python.org/3/howto/pyporting.html

I'm not suggesting you to change anything. It's just a note...

**Comment by kba** [comment]
We could really just do the 2to3 print conversions, it won't break 2.7 and it will work out-of-the-box on systems with newer default python, like Arch Linux.

**Comment by zuphilip** [comment]
Cf. https://github.com/UB-Mannheim/hocr-tools/commit/e5fbb83b7206322b79d5d3e9be1c8cd8a9e61ab5 . But I guess we should also update then the travis tests, because the conversion there is not anymore needed?

**Comment by amitdo** [comment]
https://docs.python.org/3/howto/pyporting.html#make-sure-you-specify-the-proper-version-support-in-your-setup-py-file

**Comment by zuphilip** [comment]
Closed in https://github.com/tmbdev/hocr-tools/pull/73
