### ISSUE TITLE
Does hocr-pdf suports Japanese ?

### ISSUE THREAD

**Issue by dinosauria123** [tmbdev/hocr-tools#38]
I try to make a searchable pdf by hocr-pdf.
I made gcv2hocr to make hocr from Google Cloud Vision OCR output.
https://github.com/dinosauria123/gcv2hocr
English image conversion seems to be good, I try to Japanese image conversion.

I found hocr-pdf output of pdf using Japanese included hocr, text position is much displaced.
I can't separate the problem comes from my gcv2hocr or hocr-pdf, I want to ask your opinion.

I know baseline number is important for text position in pdf file.
Could you tell me what is another important parameter for text position in pdf file ?

`<span class='ocr_line' id='line_1_1' title="bbox 96 79 127 144 ; baseline 0 -10; x_size 89; x_descenders 20; x_ascenders 21"><span class='ocrx_word' id='word_1_1' title='bbox 96 79 127 144 ; x_wconf 85' lang='jpn' dir='ltr'>  光学  </span> `

[jptest.hocr.txt](https://github.com/tmbdev/hocr-tools/files/438363/jptest.hocr.txt)
[jptest2.pdf](https://github.com/tmbdev/hocr-tools/files/438364/jptest2.pdf)
[jptest2](https://cloud.githubusercontent.com/assets/3067670/17991693/e5a6365a-6b7b-11e6-8fd8-cca65536a4b4.jpg)

**Comment by zuphilip** [comment]
The `bbox` property is important for correct placing the text in the pdf.

I tried your picture with tesseract
```
tesseract -l jpn jptest.jpg out hocr
```
and the output in the pdf seems better aligned. Maybe, you can compare the coordinates with your file.

[output-tesseract.hocr.txt](https://github.com/tmbdev/hocr-tools/files/438704/output-tesseract.hocr.txt)
[output-tesseract.pdf](https://github.com/tmbdev/hocr-tools/files/438708/output-tesseract.pdf)

**Comment by dinosauria123** [comment]
Thank you for your kindly answer every time.
I checked Tesseract OCR output  and json output from Google Cloud Vision OCR.

I found GCV output of the second x-coordinate of the word is displaces twice in Japanese recognition. 
I will check father and improve my gcv2hocr.

**Comment by dinosauria123** [comment]
Thank you for making hocr-pdf. I could convert many old Japanese scanned data to searchable pdf.

After recent update of hocr-pdf, text in the pdf file are completely broken.
It looks like €•‚ƒ „... ( †‡ˆ‰ Š‹Œ•Ž• (original Japanese text as 光学文字認識(こうがくもじにんしき)

The hocr file was made my gcv2hocr, Japanese character is correctly readable.

If you something know this issue, please answer about it
![page001](https://user-images.githubusercontent.com/3067670/53542839-a48cc200-3b63-11e9-8644-49dc931c9601.jpg)
[out.pdf](https://github.com/tmbdev/hocr-tools/files/2913483/out.pdf)
