### ISSUE TITLE
Duplicate content in <html>

### ISSUE THREAD

**Issue by CharlesNepote** [tmbdev/hocr-tools#58]
Using hocr-split, the produced files contains duplicate content:
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" xml:lang="en">
```

xmlns and xml:lang attributes are duplicated.
Then W3 validator produce errors -- see https://validator.w3.org/

**Comment by kba** [comment]
Can you please provide input files and how you called the script, so we can reproduce and fix?

**Comment by stweil** [comment]
Confirmed with

    ./hocr-split test/testdata/tess.hocr /tmp/tess-%d.hocr

**Comment by kba** [comment]
We need to be specific about the parser to use: https://bugs.launchpad.net/lxml/+bug/689928
