### ISSUE TITLE
hocr-check complains assert doc.xpath("//meta[@name='ocr-id']")!=[]

### ISSUE THREAD

**Issue by CharlesNepote** [tmbdev/hocr-tools#59]
Can be reproduced with both tesseract and gImageReader hOCR files.
https://github.com/manisandro/gImageReader/issues/101

Does the script end with this error or is it still checking the other issues?

**Comment by kba** [comment]
I would recommend you to use [hocr-spec-python](https://github.com/kba/hocr-spec-python). It's an explicit replacement for hocr-check which is more or less nonsensical at the moment.

**Comment by kba** [comment]
You can try it online here: http://digi.bib.uni-mannheim.de/ocr-fileformat/#validate

**Comment by CharlesNepote** [comment]
Every file I try to upload to hocr-spec-python ends with "NameError: global name 'KeyErrora' is not defined" (from tesseract or gImageReader).

**Comment by kba** [comment]
`KeyErrora` is a typo in https://github.com/kba/hocr-spec-python/blob/dc6377b8b46d1cb81a8571ad71c22746758bb1a2/hocr_spec/spec.py#L410. I'll fix it, thanks.

**Comment by kba** [comment]
Should be fixed and deployed.

**Comment by zuphilip** [comment]
However, the main problem here we should also fix in `hocr-check`:
 * `ocr-id` should be replaced with `ocr-system` in the check itself and the tests
 * Then we are again conform with the specs.
 * Also current Ocropus outputs looks like this: https://github.com/kba/ocr-fileformat-samples/blob/master/samples/hocr/1.1/433934212_0017.html

I can do this change, but just want to make sure, that we agree here.

**Comment by kba** [comment]
Before you implement this further, I have a branch somewhere where I've done that, let me check.

**Comment by kba** [comment]
Ah, no I did not actually fix it, so yeah: `ocr-id` should be `ocr-system`. I would probably remove the containment checks and concentrate on the bounding box overlap check since that is actually an interesting check. And I don't think it's in the specs BTW.

Should we maybe use hocr-spec-python as a base to reorganize this (#42)? The parsing of `title=` attributes could come in handy.

**Comment by CharlesNepote** [comment]
I agree that `ocr-id` should be `ocr-system`.

**Comment by zuphilip** [comment]
I created a simple fix in PR #61 . We can also improve on that the `ocr-check` but maybe we should then open another issue for that to discuss further.

**Comment by kba** [comment]
Checking whether `ocr_line` is within `ocr_page` does not tell you much. Of course it should be checked but it's rather minor and only checking three classes seems arbitrary.

What's more important is that `ocr_column` is not in the spec anymore, this should be `ocr_carea`.
