### ISSUE TITLE
hocr-check complains: not ok 2 - //meta[@name='ocr-recognized']

### ISSUE THREAD

**Issue by CharlesNepote** [tmbdev/hocr-tools#63]
But I can't see `ocr-recognized` in the hOCR spec. Is this property relevant?

**Comment by kba** [comment]
That was the name of `ocr-capabilities`, waaaaaay back when. Should be corrected.

**Comment by zuphilip** [comment]
I.e. we should replace `ocr-recognized` with `ocr-capabilites` here:
https://github.com/tmbdev/hocr-tools/search?utf8=%E2%9C%93&q=ocr-recognized&type=Code
