### ISSUE TITLE
Release v1.0.1

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/hocr-tools#65]
We fixed some bugs, did a lot of cleanup and started some other work. Thus I think we should create a new release soon. Here is my draft:

---

### Fixed bugs
 * hocr-split: Duplicate content in `<html>` https://github.com/tmbdev/hocr-tools/issues/58
 * hocr-pdf: `ocr_line` does not have to be a `span` (e.g. also a `div` is possible) https://github.com/tmbdev/hocr-tools/pull/57
 * ~~hocr-pdf: empty `rawtext` caused index error https://github.com/tmbdev/hocr-tools/pull/57~~
 * hocr-check: Fix containment checks and metadata checks, add tests https://github.com/tmbdev/hocr-tools/pull/52 https://github.com/tmbdev/hocr-tools/pull/61 https://github.com/tmbdev/hocr-tools/pull/62

### Ongoing work
 * Check handling of non ASCII characters in hOCR files https://github.com/tmbdev/hocr-tools/issues/53
 * Make hocr-tools fit for Python 3 https://github.com/tmbdev/hocr-tools/issues/37

See details: https://github.com/tmbdev/hocr-tools/compare/v1.0.0...master

---

Any comments or approvings are appreciated.

**Comment by kba** [comment]
> hocr-pdf: empty rawtext caused index error #57

Was that a bug in 1.0.0?

**Comment by zuphilip** [comment]
>> hocr-pdf: empty rawtext caused index error #57
>
>Was that a bug in 1.0.0?


I would say that https://github.com/dinosauria123/gcv2hocr/pull/3#issuecomment-247498361 is the bug report which lies on some intermediate version but I guess that we could also come up with another example which would raise the exception in `v1.0.0`. No? What would you suggest?

**Comment by kba** [comment]
That bug was introduced by
https://github.com/tmbdev/hocr-tools/pull/57/commits/64f33995e82cee7c8926ede13e35feb1f8acb0fa
and fixed by the other commit #57

**Comment by zuphilip** [comment]
Okay, then I will just delete this line.

**Comment by zuphilip** [comment]
Released https://github.com/tmbdev/hocr-tools/releases/tag/v1.0.1
