### ISSUE TITLE
Python PEP 8: Imports should usually be on separate lines

### ISSUE THREAD

**Issue by amitdo** [tmbdev/hocr-tools#68]
https://www.python.org/dev/peps/pep-0008/#imports

**Comment by amitdo** [comment]
You may want to use this tool:
https://pypi.python.org/pypi/pep8

**Comment by zuphilip** [comment]
[This is related to #15]

There are quite a lot of things which are not following the PEP 8 coding style guidelines. We activated it in our automatic test once: https://travis-ci.org/UB-Mannheim/hocr-tools/builds/131389791. If you want to help us on this, we are happy to accept any PR.

**Comment by amitdo** [comment]
Hi @zuphilip!

Do you prefer that I will send multiple PRs or one PR that fix all the issues that that the tool reports?

**Comment by stweil** [comment]
Single PRs which fix single issues can be easier reviewed, therefore I'd prefer multiple PRs.

**Comment by kba** [comment]
Do we want pep8 compliance? I was under the impression that we didn't hence the disabled checks in travis.

**Comment by stweil** [comment]
The discussion on PEP 8 and coding style was some months ago, see issues #14 and #15. We decided to focus on functionality and unit tests before addressing coding style issues. IMHO there was a good progress in these areas, so maybe it is now possible to address style issues. I'd start with fixing single issues (like separating imports) and try to reach PEP 8 until end of the year.
