### ISSUE TITLE
README: Link to hOCR format spec

### ISSUE THREAD

**Issue by amitdo** [tmbdev/hocr-tools#80]
Maybe you don't know this project: 
https://github.com/kba/hocr-spec
:laughing:

**Comment by zuphilip** [comment]
Yes, we should change the link(s) to the GoogleDocs document to the `hocr-spec`. There are actually two links given at the moment, which seems unneccessary for me:

> There is a [Public Specification](http://docs.google.com/View?docid=dfxcv4vc_67g844kf) for the hOCR Format.
>
> [...]
>
> ## Pointers
> 
> The format itself is defined here:
> 
> http://docs.google.com/View?docID=dfxcv4vc_67g844kf&revision=_latest

We can change the link to either
 * https://github.com/kba/hocr-spec (the `hocr-spec` repo itself)
 * http://kba.github.io/hocr-spec/1.2/ (the html version of the 1.2 specs)
 * http://hocr.info/ (a redirect by tmbdev)

Any suggestions? We could also think about, whether we want a redirect to the latest version, i.e. http://kba.github.io/hocr-spec/ redirects to the latest version.

**Comment by amitdo** [comment]
I prefer this link.
https://github.com/kba/hocr-spec
but the other links are also fine.

**Comment by kba** [comment]
I'd be for http://hocr.info. That redirects to the https://github.com/kba/hocr-spec which prominently links to http://kba.github.io/hocr-spec/1.2/. And it's short and on-purpose.

**Comment by zuphilip** [comment]
Changed by b4c56f85aa95bf4e946447365f53f3e99f7d80f0.
